name: Detectar Cambios en Selectores

on:
  push:
    branches:
      - Rod # o la rama que utilices

jobs:
  detectar-cambios:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout del c贸digo
      uses: actions/checkout@v4
      with:
        fetch-depth: 2 # Para obtener el commit anterior y actual

    # 2. Detectar archivos HTML modificados
    - name: Obtener cambios en archivos HTML
      id: cambios
      run: |
        # Obtener los archivos HTML modificados
        git diff --name-only HEAD~1 HEAD -- '*.html' > archivos_modificados.txt

        # Mostrar los archivos modificados en la consola
        echo "Archivos HTML modificados:"
        cat archivos_modificados.txt

        # Guardar la lista de archivos como variable de salida
        archivos=$(cat archivos_modificados.txt | tr '\n' ' ')
        echo "archivos=$archivos" >> $GITHUB_ENV

    # 3. Mostrar diferencias detalladas en cada archivo
    - name: Mostrar diferencias detalladas
      if: env.archivos != ''
      run: |
        for archivo in $archivos; do
          echo " Cambios detectados en el archivo: $archivo"
          git diff HEAD~1 HEAD -- $archivo
        done

    # 4. Subir el archivo de cambios como artefacto
    - name: Subir archivo de cambios como artefacto
      if: env.archivos != ''
      uses: actions/upload-artifact@v3
      with:
        name: archivos-modificados
        path: archivos_modificados.txt

    # 5. (Opcional) Enviar notificaci贸n por correo electr贸nico
    - name: Enviar notificaci贸n por correo electr贸nico (Opcional)
      if: env.archivos != ''
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "[Alerta] Cambios en selectores HTML detectados"
        body: |
          Se han detectado cambios en los siguientes archivos HTML:
          $archivos

          Por favor, revisa el repositorio para verificar si es necesario actualizar los selectores en tus pruebas Selenium.

          Commit: ${{ github.event.head_commit.url }}
        to: tu_correo@example.com
        from: GitHub Actions <rodrigomtz85@gmail.com>
